sudo: false
language: node_js
node_js:
- node
- 7
cache:
  directories:
    - node_modules
script:
- npm pack

deploy:
  provider: packagecloud
  edge:
    source: computology/dpl
    branch: pcloud_npm
  username: capotej
  repository: node-test
  token: "${PACKAGECLOUD_TOKEN}"
  distro: node
  package_glob: *.{tgz}
  skip_cleanup: true
  on:
    all_branches: true

notifications:
  email:
    recipients:
    - julio@packagecloud.io
    on_success: change
    on_failure: always
